name: Docker Test

on:
  push:
    # Test `develop`
    branches:
      - develop
      #- dev
      #- main

  # Run tests for any PRs.
  pull_request:

env:
  IMAGE_NAME: mosquitto

jobs:
  # Run tests.
  # See also https://docs.docker.com/docker-hub/builds/automated-testing/
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run tests
        run: |
          if [ -f docker-compose.test.yml ]; then
            docker-compose --file docker-compose.test.yml build
            docker-compose --file docker-compose.test.yml run sut
          else
            docker build \
            --secret id=MTC_PASSWD,env=MTC_PASSWD \
            --secret id=MTC_USRNAME,env=MTC_USRNAME \
            --secret id=MTC_ODS_USRNAME,env=MTC_ODS_USRNAME \
            --secret id=MTC_ODS_PASSWD,env=MTC_ODS_PASSWD \
            --build-arg MTC_USRNAME="${MTC_USRNAME}" \
            --build-arg MTC_PASSWD="${MTC_PASSWD}" \
            --build-arg MTC_ODS_USRNAME="${MTC_ODS_USRNAME}" \
            --build-arg MTC_ODS_PASSWD="${sMTC_ODS_PASSWD}" . --file Dockerfile
          fi

